language: c++
compiler:
  - clang
  - gcc
before_install:
  - git submodule update --init --recursive
install:
  - mkdir build64
  - cd build64
  - cmake ..
  - cd ..
script: cd build64 && make && ./bin/test/Glare_unit_test
