language: c++
compiler:
  - clang
  - gcc
before_install:
  - git submodule update --init --recursive
install:
  - cmake -E make_directory build64
  - cd build64
  - cmake -DCMAKE_INSTALL_PREFIX=bin -G "Visual Studio 15 2017 Win64" ..
  - cd ..
script: cmake --build build64 --config Release . && ./build64/bin/test/Glare_unit_test
