sudo: required
dist: trusty
language: c++
before_install:
  - git submodule update --init --recursive
install:
  - mkdir build64
  - cd build64
  - cmake ..
  - cd ..
script: cd build64 && make && ./bin/test/Glare_unit_test
compiler: gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
    packages:
      - xorg-dev
      - libglu1-mesa-dev
      - g++-7
env: COMPILER=g++-5
