language: c++
compiler:
  - clang
  - gcc
before_install:
  - git submodule update --init --recursive
  - chmod +x travis_before_build.sh
install: ./travis_before_build.sh
script: cmake --build . --config Release && ./build64/bin/test/Glare_unit_test
